swagger: '2.0'
info:
  title: Emotion-Based Music Recommendation API
  description: API for managing emotions and generating music recommendations based on emotions
  version: 1.0.0
host: api.example.com
basePath: /
schemes:
  - https
produces:
  - application/json
consumes:
  - application/json
paths:
  /emotions:
    get:
      summary: Get all emotions
      description: Retrieve a list of all emotions that the API uses
      operationId: getEmotions
      responses:
        '200':
          description: A list of emotions
          schema:
            type: array
            items:
              type: object
          examples:
            application/json:
              - id: 1
                name: Furious
              - id: 2
                name: Frustrated
  
  /emotions/{id}:
    get:
      summary: Get emotion by ID
      description: Retrieve a specific emotion by its ID
      operationId: getEmotionById
      parameters:
        - name: id
          in: path
          description: ID of the emotion to retrieve
          required: true
          type: integer
      responses:
        '200':
          description: A specific emotion
          schema:
              type: object
          examples:
            application/json:
              id: 7
              name: Happy
        '404':
          description: Emotion not found
  
  /emotions/{name}:
    get:
      summary: Get emotion ID by name
      description: Retrieve a specific emotion ID by its name
      operationId: getEmotionByName
      parameters:
        - name: name
          in: path
          description: Name of the emotion to retrieve
          required: true
          type: string
      responses:
        '200':
          description: The ID of the emotion
          schema:
            type: object
            properties:
              id:
                type: integer
          examples:
            application/json:
              id: 7
        '404':
          description: Emotion not found
  
  /emotions/{id}/opposite:
    get:
      summary: Get opposite emotion by ID
      description: Retrieve the opposite emotion for a given emotion ID
      operationId: getOppositeEmotionById
      parameters:
        - name: id
          in: path
          description: ID of the emotion to find the opposite for
          required: true
          type: integer
      responses:
        '200':
          description: The opposite emotion
          schema:
            type: string
          examples:
            application/json:
              id: 11
              name: Unhappy
        '404':
          description: Emotion not found
  
  /emotions/{name}/opposite:
    get:
      summary: Get opposite emotion by name
      description: Retrieve the opposite emotion for a given emotion name
      operationId: getOppositeEmotionByName
      parameters:
        - name: name
          in: path
          description: Name of the emotion to find the opposite for
          required: true
          type: string
      responses:
        '200':
          description: The opposite emotion
          schema:
            $ref: '#/definitions/Emotion'
          examples:
            application/json:
              id: 7
              name: Happy
        '404':
          description: Emotion not found
  
  /playlists:
    get:
      summary: Get all playlists
      description: Retrieve all playlists created by the current user
      operationId: getPlaylists
      responses:
        '200':
          description: A list of playlists
          schema:
            type: array
            items:
              $ref: '#/definitions/Playlist'
          examples:
            application/json:
              - id: 1
                uri: 7CY7BLvxnRa2X64BxRggJN
              - id: 2
                uri: 3ZE0WhqnsrdZHMKqZ4pCZx
        '401':
          description: Unauthorized
      security:
        - spotify_auth: []
    
    post:
      summary: Create a playlist
      description: Create a new playlist on the user's Spotify account
      operationId: createPlaylist
      parameters:
        - name: playlist
          in: body
          description: Playlist to create
          required: true
          schema:
            type: object
            properties:
              name:
                type: string
                example: happy
              tracks:
                type: array
                items:
                  $ref: '#/definitions/Track'
      responses:
        '201':
          description: Playlist created
          schema:
            type: object
            properties:
              playlist_id:
                type: string
              tracks:
                type: array
                items:
                  $ref: '#/definitions/Track'
          examples:
            application/json:
              playlist_id: 7CY7BLvxnRa2X64BxRggJN
              tracks:
                - artists: Robyn
                  titel: Dancing On My Own
                - artists: Justin Timberlake
                  titel: Cry Me a River
        '400':
          description: Bad request
        '401':
          description: Unauthorized
      security:
        - spotify_auth: []
  
  /playlists/{id}:
    get:
      summary: Get playlist by ID
      description: Retrieve a specific playlist by its ID
      operationId: getPlaylistById
      parameters:
        - name: id
          in: path
          description: ID of the playlist to retrieve
          required: true
          type: integer
      responses:
        '200':
          description: A specific playlist
          schema:
            $ref: '#/definitions/Playlist'
          examples:
            application/json:
              id: 1
              uri: 29TyOo4cPCydCPpGpVXBdA
        '401':
          description: Unauthorized
        '404':
          description: Playlist not found
      security:
        - spotify_auth: []
  
  /recommendations/emotion:
    get:
      summary: Get emotion recommendation
      description: Generate an emotion based on a user prompt
      operationId: getEmotionRecommendation
      parameters:
        - name: prompt
          in: query
          description: User text prompt for emotion analysis
          required: true
          type: string
      responses:
        '200':
          description: The recommended emotion
          schema:
            type: string
          examples:
            application/json: happy
        '400':
          description: Bad request
  
  /recommendations/songs/{id}:
    get:
      summary: Get song recommendations by emotion ID
      description: Generate song recommendations based on an emotion ID
      operationId: getSongRecommendationsById
      parameters:
        - name: id
          in: path
          description: ID of the emotion for recommendations
          required: true
          type: integer
      responses:
        '200':
          description: Track recommendations
          schema:
            type: object
            properties:
              tracks:
                type: array
                items:
                  $ref: '#/definitions/Track'
          examples:
            application/json:
              tracks:
                - artists: Robyn
                  titel: Dancing On My Own
                - artists: Justin Timberlake
                  titel: Cry Me a River
        '404':
          description: Emotion not found
  
  /recommendations/songs/{emotion}:
    get:
      summary: Get song recommendations by emotion name
      description: Generate song recommendations based on an emotion name
      operationId: getSongRecommendationsByEmotion
      parameters:
        - name: emotion
          in: path
          description: Name of the emotion for recommendations
          required: true
          type: string
      responses:
        '200':
          description: Track recommendations
          schema:
            type: object
            properties:
              tracks:
                type: array
                items:
                  $ref: '#/definitions/Track'
          examples:
            application/json:
              tracks:
                - artists: Robyn
                  titel: Dancing On My Own
                - artists: Justin Timberlake
                  titel: Cry Me a River
        '404':
          description: Emotion not found
